### ISSUE TITLE
examples aren't working

### ISSUE THREAD

**Issue by kostyrevaa** [invadersmustdie/puppet-catalog-test#16]
echo > /tmp/rakefile << EOF
require 'puppet-catalog-test'

namespace :catalog do
  PuppetCatalogTest::RakeTask.new(:all) do |t|
    t.module_paths = ["modules"]
    t.manifest_path = File.join("scripts", "site.pp")

    t.include_pattern = ENV["include"]
    t.exclude_pattern = ENV["exclude"]
  end
end
EOF

$ rake -f /tmp/rakefile
rake aborted!
Don't know how to build task 'default'

**Comment by jovandeginste** [comment]
Long time since your problem report, however:

rake -f Rakefile catalog:all

or add this line in the Rakefile:

task :default => "catalog:all"

This is what the namespace and the task ':all' means...

However, this still fails for me, but I'm still looking at the hiera integration...

**Comment by invadersmustdie** [comment]
As @jovandeginste stated you need to call the "catalog:all" task you've defined in

```ruby
namespace :catalog do
  PuppetCatalogTest::RakeTask.new(-->TASK :all <-- TASK) do |t|
    t.module_paths = ["modules"]
    t.manifest_path = File.join("scripts", "site.pp")

    t.include_pattern = ENV["include"]
    t.exclude_pattern = ENV["exclude"]
   end
end
```

I've just added a working Rakefile to each of the use-cases in the test/cases directory. I hope that helps.

**Comment by jovandeginste** [comment]
Just FYI: got it working with hiera.

**Comment by kostyrevaa** [comment]
Thanks for fixing this but I'm using puppet no more(
