### ISSUE TITLE
Not puppet 4 compatible

### ISSUE THREAD

**Issue by alexharv074** [invadersmustdie/puppet-catalog-test#18]
Wondering if there's a plan to fix this for Puppet 4.

**Comment by invadersmustdie** [comment]
If puppet 4 isn't shipping an own utility to check for faulty catalogues I
will definitely strive for puppet 4 compatibility. Give me some time to
check this out. I'm planning a little hackathon in the next 2 weeks and
hope to include this feature
Am 26.05.2015 08:13 schrieb "Alex Harvey" <notifications@github.com>:

**Comment by alexharv074** [comment]
As far as I can tell, Puppet Labs favours use of puppet-rspec to both compile and run tests on catalogs.  I personally see the tests on catalogs as a bit redundant if you do integration level tests with Beaker, so I see this project as still having value.

**Comment by invadersmustdie** [comment]
Added Puppet 4 compat on master branch. I would love to get some feedback if this fits your use-case

**Comment by invadersmustdie** [comment]
Released with version 0.4.0
