### ISSUE TITLE
Add support for puppet 3.8.x (3.8.5)

### ISSUE THREAD

**Issue by pickgr** [invadersmustdie/puppet-catalog-test#21]
We currently use the puppet 3.8.5 gem with ruby 2.0.0p645.  When we upgraded the puppet-catalog-test gem from 0.3.2 to 0.4.0 - it no longer works due to this code

      # works 3.7.x
      if version.start_with?("3.7.")
        Puppet::Test::TestHelper.initialize
      end

in lib/puppet-catalog-test/puppet_adapter/puppet_3x_adapter.rb

I see this is not listed as supported in SUPPORTED_VERSIONS.md but I've verified that it does seem to work if we can change this to something like

    if version.start_with?("3.7.", "3.8.")

Not sure if there are other dependencies though?

**Comment by invadersmustdie** [comment]
Fix will be included in next release (1-2days)

**Comment by pickgr** [comment]
Thank you!

**Comment by invadersmustdie** [comment]
We've just released 0.4.1
