### ISSUE TITLE
Get facts from a PuppetDB

### ISSUE THREAD

**Issue by brettswift** [invadersmustdie/puppet-catalog-test#31]
Howdy, 

First off - I just stumbled on this today and got it up and running really quick.. this rocks!  Thanks! 

One tier in our hierarchy is external to our control repo - clientcert.  This allows us to test for new required params at the host layer, and we've been burned by this a few times.   Integrating this into the CI process will catch that.

Anyways, my ask/question: 

Custom facts have to go into the scenario yaml file, and when you introduce a new one or use a module that uses it's own,  you have to update that file.  This isn't that big of a deal..  however, I'm wondering if there might be an easier option. 

Have you thought of sourcing facts from a PuppetDB HTTP API?   Presumably you would have to model each scenario with a sample node.  Removing that node from your datacenter or puppetdb would fail your tests.. but it might be a nice feature to have?

**Comment by scoopex** [comment]
Fetching facts from puppetdb would be great because this helps to get a realistic catalog test for a entire environment.
