### ISSUE TITLE
Puppet 5 not supported

### ISSUE THREAD

**Issue by Kriechi** [invadersmustdie/puppet-catalog-test#36]
Running catalog tests on Puppet 5 fails due to https://github.com/invadersmustdie/puppet-catalog-test/blob/780e449787a3ac5e63ee1862703fe78c56f5a795/lib/puppet-catalog-test/puppet_adapter_factory.rb#L16
which fails even harder with:

```
** Invoke catalog:all (first_time)
** Execute catalog:all
rake aborted!
NameError: uninitialized constant PuppetCatalogTest::PuppetAdapterFactory::RuntimeException
Did you mean?  RuntimeError
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-catalog-test-0.4.2/lib/puppet-catalog-test/puppet_adapter_factory.rb:16:in `create_adapter'
```

Fixing puppet to `~> 4.0` in my Gemfile fixes this, but I would like to use Puppet 5.

**Comment by madAndroid** [comment]
@Kriechi - #37 should fix this - could you try it out?
