### ISSUE TITLE
Allow all users access to packaged files in gem

### ISSUE THREAD

**Issue by varac** [invadersmustdie/puppet-catalog-test#38]
After updating to 0.4.3, I found that files inside the gem have too restricted permissions:

```
# ls -al vendor/ruby/2.1.0/gems/puppet-catalog-test-0.4.3/
total 36
drwxr-xr-x  4 root root 4096 Dec 21 09:12 .
drwxr-xr-x 58 root root 4096 Dec 21 09:12 ..
drwxr-xr-x  2 root root 4096 Dec 21 09:12 bin
drwxr-xr-x  3 root root 4096 Dec 21 09:12 lib
-rw-r--r--  1 root root 1058 Dec 21 09:12 LICENSE
-rw-------  1 root root  716 Dec 21 09:12 puppet-catalog-test.gemspec
-rw-------  1 root root 2751 Dec 21 09:12 Rakefile
-rw-------  1 root root 7477 Dec 21 09:12 README.md
```

This breaks setups where bundled gems are installed by root but accessed by an unprivileged user.

Please relax the permissions.

**Comment by invadersmustdie** [comment]
damn :/ Sorry for that .. I've uploaded 0.4.4 with fixed permissions. Could you do me the favour and verify this issue on your side?

**Comment by varac** [comment]
@invadersmustdie Sorry, I don't have the time at the moment.

**Comment by invadersmustdie** [comment]
No worries, I've verified this on another box.

1. Install gem as root
2. require + test as user

Works :)
